<a href="https://colab.research.google.com/github/journey-Ji/Python-Data-Image/blob/main/Numpy%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기본 사용법

Numpy ? 
다차원 배열을 효과적으로 처리하는 도구


In [4]:
import numpy as np

list_data=[1,2,3] #리스트를 생성
array=np.array(list_data) #리스트를 numpy로 불러와서 저장
print(list_data)
print(array.dtype)
print(array[2])
#위 처럼numpy는 list와 같이 사용할 수 있다.

[1, 2, 3]
int64
3


Numpy로 0부터 3까지의 배열 만들기

In [18]:
import numpy as np

array1=np.arange(4)#입력값-1 까지의 숫자까지 배열 출력
print(array1,'\n')

array2=np.zeros((4,4),dtype=float)#4*4의 배열, 초깃값=0, type=float
print(array2,'\n')

array3= np.ones((3,3),dtype=str)
print(array3,'\n')

array4=np.random.randint(0,10,(4,4))
print(array4,'\n')

# 평균이 0이고, 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0,1,(3,3))
print(array5)



[0 1 2 3] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']] 

[[6 8 5 7]
 [0 7 5 6]
 [5 1 8 1]
 [5 4 6 0]] 

[[ 0.64593759 -1.49024322 -0.58568673]
 [ 0.58188087  1.60197908 -0.55375139]
 [-0.65357494  0.92870195 -1.34042565]]
-0.865182441377203


Numpy 배열 합치기

In [20]:
import numpy as np
array1 =np.array([1,2,3])
array2=np.array([4,5,6])
array3=np.concatenate([array1,array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


Numpy 배열 형태 바꾸기

In [22]:
import numpy as np

array1=np.array([1,2,3,4])
array2=array1.reshape((2,2))
print(array2.shape)
print(array2)

(2, 2)
[[1 2]
 [3 4]]


Numpy 배열 세로 축으로 합치기

In [24]:
import numpy as np
array1=np.arange(4).reshape(1,4)
array2=np.arange(8).reshape(2,4)

print(array1,'\n')
print(array2,'\n')

array3=np.concatenate([array1,array2],axis=0)#axis=0 값을 부여하면 세로로 데이터가 합쳐진다.
print(array3)



[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


Numpy 배열 나누기

In [30]:
import numpy as np

array=np.arange(8).reshape(2,4)
left,right =np.split(array,[2],axis=1)# axis=1은 열을 기준으로 배열을 나눈다.
print(left.shape)
print(right.shape)
print(array)
print(right)
print(right[1][1])




(2, 2)
(2, 2)
[[0 1 2 3]
 [4 5 6 7]]
[[2 3]
 [6 7]]
7


Numpy 